### ISSUE TITLE
SPECFEM compilation failed on Summit

### ISSUE THREAD

**Issue by wjlei1990** [SPECFEM/scaling-benchmarks#2]
Hi Daniel,

The compilation no longer works on Summit. The errors shows as:
```
/sw/summit/xl/16.1.1-1/xlf/16.1.1/bin/.orig/xlf2008_r: 1501-295 (W) The -qstrict option is unsupported by IPA Link. The strict settings defined in the compilation unit will be used and processing continues without this option.
1586-403 (U) Library file "cudart" not found.
make: *** [bin/xspecfem3D] Error 1
compilation failed, please check...
```
I am not sure what happens becuase before the  New Year I can still compile the code on Summit...

Do you have any idea?

**Comment by rzurob** [comment]
To debug this, please specify `-qversion -V` on the xlf2008_r command that produced the error.  One line in the output will start with `export XL_CONFIG=`.  Open the file specified in that line and search for `cuda_libdirs_64`.  The line should contain an `-L<dir>` command pointing to the directory containing libcudart.*.  If it doesn't, or if that directory does not contain the library, it means the cuda installation was moved or removed.  If it was moved, you'll need to regenerate the compiler configuration file.

**Comment by rzurob** [comment]
If the above does not help, please post the output from adding `-V` to the xlf2008_r step above.  That option shows the commands the compiler invoked and the options it passed to them.  (Please redirect stdout and stderr to separate files)

**Comment by rdno** [comment]
Hi,

I can compile the up-to-date version of SPECFEM (8415dc) with Daniel's scripts. Are you using anything different?

**Comment by wjlei1990** [comment]
Sorry, it is my fault. I forgot to re-configure the code...I think there are some module changes so when I compile it without re-configure, the compile frailed.

It is fixed now so I will close it.
